name: 'Setup ORT Server CLI'
description: 'Setup the ORT Server CLI (OSC) to use in GitHub workflows.'
inputs:
  osc-version:
    description: 'The version of the ORT Server CLI to install. Defaults to latest if not specified.'
    required: false
    default: latest
  url:
    description: 'The base URL of the ORT Server instance'
    required: false
  token-url:
    description: 'The URL to request a token for the ORT Server instance'
    required: false
  client-id:
    description: 'The client ID to authenticate with the ORT Server instance'
    required: false
  username:
    description: 'The username to authenticate with the ORT Server instance'
    required: false
  password:
    description: 'The password to authenticate with the ORT Server instance'
    required: false

# language=bash
runs:
  using: composite
  steps:
    - name: Download OSC
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        OSC_VERSION: ${{ inputs.osc-version }}
      run: |
        if [ -z "$OSC_VERSION" -o "$OSC_VERSION" = "latest" ]; then
          OSC_VERSION=$(gh release view -R eclipse-apoapsis/ort-server --json tagName --jq .tagName)
        fi

        OSC_HOME=$RUNNER_TOOL_CACHE/osc/$OSC_VERSION

        if [ ! -d "$OSC_HOME" ]; then
          LOWERCASE_OS=$(echo $RUNNER_OS | tr '[:upper:]' '[:lower:]')
          LOWERCASE_ARCH=$(echo $RUNNER_ARCH | tr '[:upper:]' '[:lower:]')

          echo "::notice::Setting up OSC version $OSC_VERSION ($LOWERCASE_OS-$LOWERCASE_ARCH) in '$OSC_HOME'..."

          # https://cli.github.com/manual/gh_release_download
          gh release download $OSC_VERSION -R eclipse-apoapsis/ort-server -p osc-cli-$LOWERCASE_OS-$LOWERCASE_ARCH*

          mkdir -p "$OSC_HOME"

          if [ "$LOWERCASE_OS" = "windows" ]; then
            unzip osc-cli-$LOWERCASE_OS-$LOWERCASE_ARCH.zip -d "$OSC_HOME"
          else
            tar -xzf osc-cli-$LOWERCASE_OS-$LOWERCASE_ARCH.tar.gz -C "$OSC_HOME"
          fi

          echo "$OSC_HOME" >> "$GITHUB_PATH"
        else
          echo "::notice::OSC version $OSC_VERSION is already set up in '$OSC_HOME'."
        fi

    - name: Configure Authentication
      if: ${{ inputs.url != '' && inputs.username != '' && inputs.password != '' }}
      shell: bash
      run: |
        TOKEN_URL_ARG=""
        if [[ -n "${{ inputs.token-url }}" ]]; then
          TOKEN_URL_ARG="--token-url ${{ inputs.token-url }}"
        fi

        CLIENT_ID_ARG=""
        if [[ -n "${{ inputs.client-id }}" ]]; then
          CLIENT_ID_ARG="--client-id ${{ inputs.client-id }}"
        fi

        osc auth login \
          --url "${{ inputs.url }}" \
          --username "${{ inputs.username }}" \
          --password "${{ inputs.password }}" \
          $TOKEN_URL_ARG \
          $CLIENT_ID_ARG

    - name: Authentication Info
      if: ${{ inputs.url == '' || inputs.username == '' || inputs.password == '' }}
      shell: bash
      run: |
        echo "::warning::OSC is running without authentication. Either configure authentication in the 'setup-osc' action (url, username and password), or authenticate manually using 'osc auth login'."
